### ISSUE TITLE
Not working for Elixir 1.9

### ISSUE THREAD

**Issue by bossyang** [blackode/custom-iex#1]
macOS 10.14.6
elixir 1.9.1/1.9.4
```
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Interactive Elixir (1.9.4) - press Ctrl+C to exit (type h() ENTER for help)
11:36:19.166 [error] GenServer IEx.Config terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in IEx.Config.update_configuration/1
    (iex) lib/iex/config.ex:170: anonymous fn({:continuation_prompt, "    "}) in IEx.Config.update_configuration/1
    (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:783: Enum.each/2
    (iex) lib/iex/config.ex:164: IEx.Config.handle_configure/2
    (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.104.0>): {:update, {IEx.Config, :handle_configure, [[continuation_prompt: "    ", default_prompt: "\e[G\e[33m%counter. \e[35m\e[0m\e[0m"]]}}
State: IEx.Config
Client #PID<0.104.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:1006: GenServer.call/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:126: :erl_eval.exprs/5
    (elixir) src/elixir.erl:275: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:188: IEx.Evaluator.eval_dot_iex/2
    (iex) lib/iex/evaluator.ex:23: IEx.Evaluator.init/4
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Error while evaluating: /Users/bossyang/.iex.exs
** (exit) exited in: GenServer.call(IEx.Config, {:update, {IEx.Config, :handle_configure, [[continuation_prompt: "    ", default_prompt: "\e[G\e[33m%counter. \e[35m\e[0m\e[0m"]]}}, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in anonymous fn/1 in IEx.Config.update_configuration/1
            (iex) lib/iex/config.ex:170: anonymous fn({:continuation_prompt, "    "}) in IEx.Config.update_configuration/1
            (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:783: Enum.each/2
            (iex) lib/iex/config.ex:164: IEx.Config.handle_configure/2
            (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:1009: GenServer.call/3
```

**Comment by daya** [comment]
same here, it's not working

```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```
